import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import ContextProvider from "./utils/context";

const poppins = Poppins({
  weight: ['400'],
  subsets: ["latin"],
  display: "swap"
})

export const metadata: Metadata = {
  title: "heyfood.africa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <ContextProvider>
          <NavBar />
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
